### ISSUE TITLE
EPIC: Beverage Browsing and Ordering

### ISSUE THREAD

**Issue by Afjunior18** [Afjunior18/beverage_bazaar#2]

**Comment by Afjunior18** [comment]
Following User Stories link about this EPIC - EPIC 2

- [x] https://github.com/Afjunior18/beverage_bazaar/issues/20
- [x] https://github.com/Afjunior18/beverage_bazaar/issues/18
- [x] https://github.com/Afjunior18/beverage_bazaar/issues/17
- [x] https://github.com/Afjunior18/beverage_bazaar/issues/16
